version: "2"

services:
  rundeck-web-app:
    image: eugenmayer/rundeck:3.3.7.20201208-1
    container_name: rundeck-web-app
    depends_on:
      - db
    environment:
      # see .env for explainations and docs
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EXTERNAL_SERVER_URL: ${EXTERNAL_SERVER_URL}
      RUNDECK_ADMIN_PASSWORD: ${RUNDECK_ADMIN_PASSWORD}
      RDECK_JVM_SETTINGS: ${RDECK_JVM_SETTINGS}
      RUNDECK_UID: ${RUNDECK_UID}
      RUNDECK_GID: ${RUNDECK_GID}
      RUNDECK_STORAGE_PROVIDER: ${RUNDECK_STORAGE_PROVIDER}
      RUNDECK_PROJECT_STORAGE_TYPE: ${RUNDECK_PROJECT_STORAGE_TYPE}
      LOGIN_MODULE: ${LOGIN_MODULE}
      JAAS_CONF_FILE: ${JAAS_CONF_FILE}
      RUNDECK_WITH_SSL: "${RUNDECK_WITH_SSL}"
      RD_USER: admin
      RD_PASSWORD: ${RUNDECK_ADMIN_PASSWORD}
      RD_URL: http://localhost:4440
      SERVER_URL: http://localhost:4440
      RD_BYPASS_URL: ${EXTERNAL_SERVER_URL}
    #command: tail -f /dev/null
    volumes:
      - rundeck_plugins:/opt/rundeck-plugins
      - rundeck_config:/etc/rundeck
      - rundeck_logs:/var/log/rundeck
      - rundeck_storage:/var/lib/rundeck/var/storage
      - rundeck_tmp:/var/rundeck
      # mount those for your own ssh keys
      # - .keys/id_rsa:/var/lib/rundeck/.ssh/id_rsa
      # - .keys/id_rsa.pub:/var/lib/rundeck/.ssh/id_rsa.pub
    networks:
      - rundeck-app-network
  # nginx is used to deal with the OPTIONS call not implemented in rundeck, nothing else
  rundeck-rp-app:
    depends_on:
      - rundeck-web-app
    image: eugenmayer/rundeck_nginx
    container_name: rundeck-rp-app
    ports:
      - ${EXTERNAL_SERVER_PORT}:80
      - ${EXTERNAL_SERVER_SSL_PORT}:443
    networks:
      - rundeck-app-network
    volumes:
      - ./nginx/rundeck.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/:/etc/ssl/site
  db:
    image: postgres:9.6
    container_name: rundeck-db-app
    volumes:
      - rundeck_db:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - rundeck-app-network

networks:
  rundeck-app-network:
    driver: bridge
volumes:
  rundeck_config:
    driver: local
  rundeck_tmp:
    driver: local
  rundeck_storage:
    driver: local
  rundeck_logs:
    driver: local
  rundeck_plugins:
    driver: local
  rundeck_plugins:
    driver: local
  rundeck_db:
    driver: local
